version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 16
      python: 3.8
    commands:
      - echo "Installing dependencies..."
      - npm install -g aws-cdk # Ensures the CDK CLI is installed globally
      - pip install aws-cdk-lib
      - pip install constructs
      - echo "Installing Python Lambda dependencies..."
      - pip install -r lambda/requirements.txt -t lambda/
  build:
    commands:
      - echo "Synthesizing the AWS CDK stack..."
      - cdk synth
  post_build:
    commands:
      - echo "Deploying the AWS CDK stack..."
      - cdk deploy --require-approval never
artifacts:
  files:
    - '**/*' # Adjust if specific files need to be included in the build artifacts

