---
version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 16
      python: 3.8
    commands:
      - python3 -m venv ~/.venv
      - source ~/.venv/bin/activate
      - pip install -r requirements.txt
      - pip install --upgrade pip
      - pip install aws-cdk-lib constructs
      - pip install aws-cdk-lib  
  build:
    commands:
      - echo "Synthesizing the AWS CDK stack..."
      - cdk synth
      - echo "Deploying the AWS CDK stack..."
      - cdk deploy --require-approval never
