version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 16
      python: 3.8
    commands:
      - echo "Installing Node.js and npm..."
      - curl --silent --location https://rpm.nodesource.com/setup_16.x | bash -  # Correct setup for Amazon Linux
      - yum install -y nodejs  # Install Node.js and npm on Amazon Linux
      - npm install -g aws-cdk  # Install CDK globally
      - echo "Installing Python dependencies..."
      - pip install aws-cdk-lib
      - pip install constructs
      - echo "Installing Lambda dependencies..."
      - pip install -r lambda/requirements.txt -t lambda/
  build:
    commands:
      - echo "Synthesizing the AWS CDK stack..."
      - cdk synth
  post_build:
    commands:
      - echo "Deploying the AWS CDK stack..."
      - cdk deploy --require-approval never
artifacts:
  files:
    - '**/*'
