version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
      python: 3.8
    commands:
      - echo "Installing Node.js and npm..."
      - curl -sL https://rpm.nodesource.com/setup_18.x | bash -  # Install Node.js 18 (no sudo needed)
      - yum install -y nodejs  # Install Node.js and npm (this should work without sudo)
      - node -v  # Verify Node.js version
      - npm -v   # Verify npm version
      - echo "Installing AWS CDK globally..."
      - npm install -g aws-cdk  # Install AWS CDK globally
      - echo "Installing project dependencies..."
      - npm install  # Install project dependencies from package.json
      - echo "Installing Python dependencies..."
      - pip install aws-cdk-lib
      - pip install -r lambda/requirements.txt -t lambda/

  build:
    commands:
      - echo "Synthesizing the AWS CDK stack..."
      - cdk synth
      - echo "Deploying the AWS CDK stack..."
      - cdk deploy --require-approval never

artifacts:
  files:
    - '**/*'
  discard-paths: yes
