version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
      nodejs: 18  # You can try using Node.js 18 (or 20) to match the latest CDK support
    commands:
      - echo "Installing AWS CDK globally..."
      - npm install -g aws-cdk  # Install AWS CDK globally
      - echo "Installing Python dependencies..."
      - pip install aws-cdk-lib
      - pip install constructs
      - echo "Installing Lambda dependencies..."
      - pip install -r lambda/requirements.txt -t lambda/
  build:
    commands:
      - echo "Synthesizing the AWS CDK stack..."
      - cdk synth  # Directly use cdk since it's globally installed
  post_build:
    commands:
      - echo "Deploying the AWS CDK stack..."
      - cdk deploy --require-approval never  # Directly use cdk for deployment
artifacts:
  files:
    - '**/*'
