version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo "Installing Python dependencies..."
      - pip install aws-cdk-lib
      - pip install constructs
      - echo "Installing Lambda dependencies..."
      - pip install -r lambda/requirements.txt -t lambda/
  build:
    commands:
      - echo "Synthesizing the AWS CDK stack..."
      - npx cdk synth  # Use the locally installed cdk
  post_build:
    commands:
      - echo "Deploying the AWS CDK stack..."
      - npx cdk deploy --require-approval never  # Use the locally installed cdk
artifacts:
  files:
    - '**/*'
