version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 16
      python: 3.8
    commands:
      - echo "Ensuring pip is up to date..."
      - python3 -m ensurepip --upgrade
      - python3 -m pip install --upgrade pip
      - echo "Installing AWS CDK libraries..."
      - python3 -m pip install aws-cdk-lib
      - echo "Installing Python dependencies for Lambda functions..."
      - python3 -m pip install -r lambda/requirements.txt -t lambda/
  build:
    commands:
      - echo "Synthesizing the AWS CDK stack..."
      - npx cdk synth
      - echo "Deploying the AWS CDK stack..."
      - npx cdk deploy --require-approval never
