version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18 # Specify the Node.js version
    commands:
      - echo "Installing AWS CDK..."
      - npm install -g aws-cdk # Install AWS CDK globally
      - echo "Installing project dependencies..."
      - npm install # Install project dependencies from package.json

  pre_build:
    commands:
      - echo "Running pre-build phase..."
      - echo "Validating CDK installation..."
      - cdk --version # Ensure CDK is installed correctly

  build:
    commands:
      - echo "Running build phase..."
      - npm run build # Replace with your build command, if applicable
      - echo "Synthesizing CDK stack..."
      - cdk synth

  post_build:
    commands:
      - echo "Running post-build phase..."
      - echo "Deploying CDK stack..."
      - cdk deploy --require-approval never # Automatically approve changes

artifacts:
  files:
    - "**/*" # Include all files for debugging or further steps
  discard-paths: yes
